define_directive {v:work.ray_tracer_top} {.noprune} {1}
define_directive {v:work.ray_tracer_top} {.distcompnoprune} {1}
define_directive {v:work.sramb} {.noprune} {1}
define_directive {v:work.sramb} {.distcompnoprune} {1}
define_directive {v:work.streamer} {.noprune} {1}
define_directive {v:work.streamer} {.distcompnoprune} {1}
define_directive {v:work.fifo} {.noprune} {1}
define_directive {v:work.fifo} {.distcompnoprune} {1}
define_directive {v:work.ray_tracer_top} {.distcompmodetop} {1}
