set paths_array(margin_msg,1) {}
set paths_array(e_line,1) {0}
set paths_array(req_time,1) {4.857}
set paths_array(slack,1) {-1.175}
set paths_array(TS,1) {}
set paths_array(start_point,1) {P_HIT0/u_p_hit_module/u_p_hit_mult/u_p_hit_1/bottom/u_dot/u_dot_module/out_big_1[23:0]}
set paths_array(end_clk_dly,1) {0.000}
set paths_array(start_clock,1) {ray_tracer_top|clock:rising}
set paths_array(skew,1) {0.0}
set paths_array(sig) {/home/jco1147/ray_tracer/github/RayTracer/sv/top/top.prj|rev_1 {} /home/jco1147/ray_tracer/github/RayTracer/sv/top/rev_1/sdc_verif_slack.itd correlate 1 slack 1 {} {} {} {} {} {} 0 1 0 1 1}
set paths_array(margin,1) {0}
set paths_array(pro_slack,1) {0}
set paths_array(start_type,1) {reg}
set paths_array(start_clk_dly,1) {0.000}
set paths_array(index,1) {1}
set paths_array(passed,1) {0}
set paths_array(end_point,1) {P_HIT0/u_p_hit_module/u_p_hit_mult/u_p_hit_1/bottom/u_dot/u_fifo/fifo_buf.I_1.P_HIT0.u_p_hit_module.u_p_hit_mult.u_p_hit_1.bottom.u_dot.u_fifo.fifo_buf_299[31:20]}
set paths_array(end_type,1) {reg}
set paths_array(data_delay,1) {0}
set paths_array(status_msg,1) {}
set paths_array(s_line,1) {0}
set paths_array(end_clock,1) {ray_tracer_top|clock:rising}
set synth_array(start_clk_dly,1) {}
set synth_array(start_type,1) {}
set synth_array(start_point,1) {}
set synth_array(end_clk_dly,1) {}
set synth_array(end_type,1) {}
set synth_array(end_point,1) {}
set synth_array(start_clock,1) {}
set synth_array(skew,1) {}
set synth_array(slack,1) {}
set synth_array(req_time,1) {}
set synth_array(end_clock,1) {}
set sort_list {1 NA}
set clock_list {}
set foo {ctd_ta_point,P_HIT0/u_p_hit_module/u_p_hit_mult/u_p_hit_1/bottom/u_dot/u_dot_module/out_big_1[23:0]}
set ta_array($foo) {P_HIT0.u_p_hit_module.u_p_hit_mult.u_p_hit_1.bottom.u_dot.u_dot_module.out_big_1[23:0]}
set foo {ctd_ta_point,P_HIT0/u_p_hit_module/u_p_hit_mult/u_p_hit_1/bottom/u_dot/u_fifo/fifo_buf.I_1.P_HIT0.u_p_hit_module.u_p_hit_mult.u_p_hit_1.bottom.u_dot.u_fifo.fifo_buf_299[31:20]}
set ta_array($foo) {P_HIT0.u_p_hit_module.u_p_hit_mult.u_p_hit_1.bottom.u_dot.u_fifo.fifo_buf.I_1.P_HIT0.u_p_hit_module.u_p_hit_mult.u_p_hit_1.bottom.u_dot.u_fifo.fifo_buf_299[31:20]}
puts ""
